
default:
  image: node:18.18.2

stages:
  - lint
  - deploy

deploy_preview:
  stage: deploy
  except:
  - main
  script:
  - npm install --global vercel
  - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
  - vercel deploy --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
  - main
  script:
  - npm install --global vercel
  - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
  - vercel deploy --prod --token=$VERCEL_TOKEN

eslint:
  stage: lint
  script:
    - npm install eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react
    - npx eslint.