export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const AuthLayout = ({children}: { children: React.ReactNode }) => {
    return (
        <div className="h-full flex items-center justify-center">
            {children}
        </div>
    )
}

export default AuthLayout;